# Generated by Django 5.1.3 on 2024-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_burgermenu_logo_burgermenu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Instagram')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Twitter')),
                ('google_plus', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Google+')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
