# Generated by Django 5.1.3 on 2024-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerBigMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
